{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = "xprec" %}
{% set version = data.get("version") %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  buid:
    - python {{ python }}
    - numpy {{ numpy }}
  host:
    - python {{ python }}
    - numpy {{ numpy }}
  run:
    - python {{ python }}
    - numpy {{ numpy }}

#test:
#  imports:
#    - xprec
#  source_files:
#    - test/*.py
#  requires:
#    - pytest
#  commands:
#    #- pytest test/
#    - find test -name "test*.py" -not -path "*/test_whitespace.py" | xargs pytest

about:
  home: "https://github.com/tuwien-cms/xprec"
  license: MIT
  summary: "xprec precision numpy extension"

extra:
  recipe-maintainers:
    - shinaoka
