[tool.cibuildwheel]
# Skip 32-bit builds
# Disable building PyPy wheels on all platforms
#skip = ["*-win32", "*-manylinux_i686", "pp*"]
skip = ["*-win32", "pp*"]
#build = "cp36-manylinux_i686"

# Build `universal2` and `arm64` wheels on an Intel runner.
# Note that the `arm64` wheel and the `arm64` part of the `universal2`
# wheel cannot be tested in this configuration.
[tool.cibuildwheel.macos]
archs = ["x86_64", "universal2", "arm64"]

# On an Linux Intel runner with qemu installed, build Intel and ARM wheels
[tool.cibuildwheel.linux]
archs = ["auto", "aarch64"]